config/routes.rb
Rails.application.routes.draw do
  resources :objetos
  root 'home#index'
  get 'objetos/:id/destroy' => 'objetos#destroy'
  
  resources :instituicaos do
    collection do
      get 'details'
    end
  end
  post '/instituicaos/logoff' => 'instituicaos#logoff'
  
  # Rotas usuários
  resources :usuarios
    post '/usuarios/logoff' => 'usuarios#logoff'
    get '/usuarios/cadastro/doador' => 'usuarios#doador'
    get '/usuarios/cadastro/empresadoadora' => 'usuarios#empresadoadora'

  post '/usuarios/update_cidades' => 'usuarios#update_cidades'
  post '/instituicaos/update_cidades' => 'instituicaos#update_cidades'

  # Rotas login
  resources :login
    post '/login/auth' => 'login#auth'
  
  resources :layouts
  
  resources :doacaos  
    get '/doacoes/cadastro' => 'doacaos#new'
    get '/doacaos/:id/contato' => 'doacaos#contato'
    get '/doacaos/:id/conf_contato' => 'doacaos#conf_contato'
    get '/doacaos/:id/aprovar' => 'doacaos#aprovar'
    get '/doacaos/:id/back_contato' => 'doacaos#back_contato'
    
  get 'login/login'
  get 'home/index'
  get 'home/home'
  get 'home/cadastrousuariodoador'
  get 'about/about'
  get 'home/selectusertype'
  get 'instituicaos/listObjetos/:id' => 'instituicaos#listObjetos'
  
  post 'home/search' =>'home#search'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/objeto.rb
class Objeto < ApplicationRecord
  belongs_to :categoria_objeto
  validates :nome, presence: true 
  validates :unidade_medida, presence: true 
  validates :meta, presence: true
end

app/controllers/objetos_controller.rb
class ObjetosController < ApplicationController
  before_action :set_objeto, only: [:show]
  before_action :set_objeto_by_trueid, only: [:edit, :update, :destroy]

  # GET /objetos
  def index
    @objetos = Objeto.all
    @imagem
  end

  # GET /objetos/1
  def show
  end

  # GET /objetos/new
  def new
    @objeto = Objeto.new
    @categorias = CategoriaObjeto.all.order(:nome).map { |categoria| [categoria.nome, categoria.id]}.prepend(['Selecione uma categoria', 0])
  end
  
  # GET /objetos/1/edit
  def edit
    @categorias = CategoriaObjeto.all.order(:nome).map { |categoria| [categoria.nome, categoria.id]}.prepend(['Selecione uma categoria', 0])
  end

  # POST /objetos
  def create
    #teste#
    #if Instituicao.find(session[:instLogedin]) == nil
    #  Instituicao.find(session[:instLogedin]) = Instituicao.all.first
    #end
    #teste#
    
    @objeto = Objeto.new(objeto_params)
    @categorias = CategoriaObjeto.all.order(:nome).map { |categoria| [categoria.nome, categoria.id]}.prepend(['Selecione uma categoria', 0])
   
    if(session[:instLogedin])
      @objeto.instituicao_id = Instituicao.find(session[:instLogedin]).id
    else
      @objeto.instituicao_id = 0 
    end
    @objeto.is_inativo = false
    respond_to do |format|
      if @objeto.save
        format.html { render :success, :locals => {:e => 0} }
        # format.html { redirect_to @objeto, notice: 'Objeto was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def success
    @imagem
  end

  # PATCH/PUT /objetos/1
  # PATCH/PUT /objetos/1.json
  def update
    @categorias = CategoriaObjeto.all.order(:nome).map { |categoria| [categoria.nome, categoria.id]}.prepend(['Selecione uma categoria', 0])
    respond_to do |format|
      if @objeto.update(objeto_params)
        format.html { render :success, :locals => {:e => 1} }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /objetos/1
  # DELETE /objetos/1.json
  def destroy
    @instID = @objeto.instituicao_id.to_s
    @objeto.is_inativo = true
    @objeto.save
    respond_to do |format|
      format.html { redirect_to '/instituicaos/listObjetos/' + @instID }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objeto
      @objeto = Objeto.find(params[:objeto_id])
    end
    def set_objeto_by_trueid
      @objeto = Objeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objeto_params
      params.require(:objeto).permit(:categoria_objeto_id, :nome, :unidade_medida, :meta, :observacoes)
    end
end

app/helpers/objetos_helper.rb
module ObjetosHelper
end

app/views/objetos/_form.html.haml
= form_for @objeto do |f|
  - if @objeto.errors.any?
    #error_explanation
      %h2= "#{pluralize(@objeto.errors.count, "error")} prohibited this objeto from being saved:"
      %ul
        - @objeto.errors.full_messages.each do |msg|
          %li= msg
  .form 
    %fieldset
      .categoriaForm     
        %h2 Dados do Objeto
        .separador
        .itemForm
          = f.label :categoria_objeto_id, :class => "labela"
          = f.select :categoria_objeto_id, options_for_select(@categorias), {}, { :class => "inputa" }
        .itemForm
          = f.label :nome, :class => "labela"
          = f.text_field :nome, :class => "inputa"
        .itemForm
          = f.label :meta, :class => "labela"
          = f.number_field :meta, :class => "inputa"
        .itemForm
          = f.label :unidade_medida, :class => "labela"
          = f.text_field :unidade_medida, :class => "inputa"
        .itemForm
          = f.label :observacoes, :class => "labela"
          = f.text_field :observacoes, :class => "inputa"
        .separador2
        %div.div-submit-button
          = f.submit 'Finalizar', :class => "buttonForm"

app/views/objetos/edit.html.haml
%h1 Editar objeto

= render 'form'

%a{:href => '/objetos/' + @objeto.id.to_s + '/destroy', :onclick => "return confirm('Tem certeza que deseja excluir o objeto?');"}
  .categoriaForm
    .buttonForm.buttonFormRed
      Desativar

app/views/objetos/index.html.haml
 
.separador1
.h1
  Objetos Disponíveis
.separador1
.separador1
.separador2
- @objetos.each do |objeto|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = objeto.nome
      .h2 
        = objeto.observacoes
    -if session[:isInstituicao]
      %a{:href => edit_objeto_path(@usuario)}    
        .itemObjetoBotao
          .buttonlink
            EXCLUIR
    -else
      %a{:href => new_doacao_path(:objeto_id => objeto)}  
        .itemObjetoBotao
          .buttonlink
            DOAR
    .itemObjetoMeta
      %h2
        = Instituicao.find(objeto.instituicao_id).nome
      .h3
        Meta:
        = objeto.meta 
        = " "
        = objeto.unidade_medida
  .separador4
.separador1
.separador1
%a{:href => "/home/home"} 
  .button1
    .buttonlink VOLTAR
.separador1
.separador1
.separador2

app/views/objetos/listDoador.html.haml
 
.separador1
.h1
  Objetos Disponíveis
.separador1
.separador1
.separador2
- @objetos.each do |objeto|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = objeto.nome
      .h2 
        = objeto.observacoes
    .itemObjetoBotao
      .buttonlink
        DOAR
    .itemObjetoMeta
      %h2
        = Instituicao.find(objeto.instituicao_id).nome
      .h3
        Meta:
        = objeto.meta 
        = " "
        = objeto.unidade_medida
  .separador4
.separador1
.separador1
%a{:href => "/home/home"} 
  .button1
    .buttonlink VOLTAR
.separador1
.separador1
.separador2

app/views/objetos/listInstituicao.html.haml
 
.separador1
.h1
  Objetos Disponíveis
.separador1
.separador1
.separador2
- @objetos.each do |objeto|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = objeto.nome
      .h2 
        = objeto.observacoes
    .itemObjetoBotao
      .buttonlink
        EXCLUIR
    .itemObjetoMeta
      %h2
        = Instituicao.find(objeto.instituicao_id).nome
      .h3
        Meta:
        = objeto.meta 
        = " "
        = objeto.unidade_medida
  .separador4
.separador1
.separador1
%a{:href => "/home/home"} 
  .button1
    .buttonlink VOLTAR
.separador1
.separador1
.separador2

app/views/objetos/new.html.haml
%h1 Novo Objeto

= render 'form'

app/views/objetos/show.html.haml
%p#notice= notice

%p
  %b Categoria objetos:
  = @objeto.categoria_objeto.nome
%p
  %b Nome:
  = @objeto.nome
%p
  %b Unidade medida:
  = @objeto.unidade_medida
%p
  %b Meta:
  = @objeto.meta
%p
  %b Observacoes:
  = @objeto.observacoes

= link_to 'Edit', edit_objeto_path(@objeto)
\|
= link_to 'Back', objetos_path

app/views/objetos/success.html.haml
.separador1
.separador1
.separador1
-if e == 1
  %h1 Objeto atualizado com sucesso!
-else
  %h1 Objeto cadastrado com sucesso!

.separador2

%h2 Agora é só aguardar as doações
.separador1
.separador1

.separador


.itemObjeto
  .itemObjetoIcone
    -@imagem = "/images/catgs/catg" + @objeto.categoria_objeto_id.to_s +  ".png"
    %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
  .itemObjetoNome
    %h1
      = @objeto.nome
    .h2 
      = @objeto.observacoes
  %a{:href => edit_objeto_path(@objeto)}
    .itemObjetoBotao
      .buttonlink EDITAR
      
  .itemObjetoMeta
    %h2
      = Instituicao.find(session[:instLogedin]).nome
  
    .h3
      Meta:
      = @objeto.meta 
      = " "
      = @objeto.unidade_medida
.separador2
.separador1
.separador1
.separador1
.separador1

%h2 Gostaria de cadastrar mais algum objeto?
%a{:href => "/objetos/new"}    
  .buttonbig
    .buttonlink CADASTRAR
.separador1        
%a{:href => "/home/home"}    
  .buttonbig
    .buttonlink VOLTAR