config/routes.rb
Rails.application.routes.draw do
  resources :objetos
  root 'home#index'
  get 'objetos/:id/destroy' => 'objetos#destroy'
  
  resources :instituicaos do
    collection do
      get 'details'
    end
  end
  post '/instituicaos/logoff' => 'instituicaos#logoff'
  
  # Rotas usuários
  resources :usuarios
    post '/usuarios/logoff' => 'usuarios#logoff'
    get '/usuarios/cadastro/doador' => 'usuarios#doador'
    get '/usuarios/cadastro/empresadoadora' => 'usuarios#empresadoadora'

  post '/usuarios/update_cidades' => 'usuarios#update_cidades'
  post '/instituicaos/update_cidades' => 'instituicaos#update_cidades'

  # Rotas login
  resources :login
    post '/login/auth' => 'login#auth'
  
  resources :layouts
  
  resources :doacaos  
    get '/doacoes/cadastro' => 'doacaos#new'
    get '/doacaos/:id/contato' => 'doacaos#contato'
    get '/doacaos/:id/conf_contato' => 'doacaos#conf_contato'
    get '/doacaos/:id/aprovar' => 'doacaos#aprovar'
    get '/doacaos/:id/back_contato' => 'doacaos#back_contato'
    
  get 'login/login'
  get 'home/index'
  get 'home/home'
  get 'home/cadastrousuariodoador'
  get 'about/about'
  get 'home/selectusertype'
  get 'instituicaos/listObjetos/:id' => 'instituicaos#listObjetos'
  
  post 'home/search' =>'home#search'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doacao.rb
class Doacao < ApplicationRecord
  belongs_to :usuario
  belongs_to :objeto
  #status
  # 0 - pendente contato
  # 1 - pendente aprovação (apos contato)
  # 2 - cancelado
  # 3 - aprovado
end

app/controllers/doacaos_controller.rb
class DoacaosController < ApplicationController
  before_action :set_doacao, only: [:show, :edit, :update, :destroy]

  # GET /doacaos

  def index
    if session[:isInstituicao] 
      @instituicao = Instituicao.find_by(id: session[:instLogedin])
      if params[:status] == 'pendentes'
        @doacaos = Doacao.joins(:objeto).where("objetos.instituicao_id = ? and (status = 0 or status = 1)", @instituicao.id).all
      elsif params[:status] == 'aceitas'
        @doacaos = Doacao.joins(:objeto).where("objetos.instituicao_id = ? and (status = 3)", @instituicao.id).all
      else
        @doacaos = Doacao.joins(:objeto).where("objetos.instituicao_id = ? and (status = 2)", @instituicao.id).all
      end
    else
      @doacaos = nil
    end
  end
  
  # GET /doacaos/1
  
  #def show
  #end

  # GET /doacaos/new
  def new
    @doacao = Doacao.new
    @objeto = Objeto.new
  end

  # GET /doacaos/1/edit
  def edit
  end

  # POST /doacaos

  def contato
    set_doacao
  end
  
  def conf_contato
    set_doacao
    Doacao.where(:id => @doacao.id).update_all("status = 1")
    respond_to do |format|
      format.html { redirect_to '/doacaos?status=pendentes' }
    end
    #update status = 1
  end
  
  def back_contato
    set_doacao
    
    index
    respond_to do |format|
      format.html { redirect_to '/doacaos?status=pendentes' }
    end
  end
  
  def aprovar
    set_doacao
    index
    if params[:aprovar] == 'sim'
      @newVal = @doacao.objeto.meta - @doacao.quantidade
      Objeto.where(:id => @doacao.objeto.id).update_all("meta = " + (@newVal < 0 ? 0 : @newVal).to_s)
      Doacao.where(:id => @doacao.id).update_all("status = 3")
      #update status = 3
    else
      Doacao.where(:id => @doacao.id).update_all("status = 2")
      #update status = 2
    end
    respond_to do |format|
      format.html { redirect_to '/doacaos?status=pendentes' }
    end
  end
  
  def create
    @doacao = Doacao.new(doacao_params)
    respond_to do |format|
      if @doacao.save
        format.html { render :success }
        # format.html { redirect_to @doacao, notice: 'Doacao was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /doacaos/1
  # PATCH/PUT /doacaos/1.json
  def update
    respond_to do |format|
      if @doacao.update(doacao_params)
        format.html { redirect_to @doacao, notice: 'Doacao was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /doacaos/1
  # DELETE /doacaos/1.json
  def destroy
    @doacao.destroy
    respond_to do |format|
      format.html { redirect_to doacaos_url, notice: 'Doacao was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doacao
      @doacao = Doacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doacao_params
      params.require(:doacao).permit(:usuario_id, :objeto_id, :quantidade, :observacoes, :status)
    end
end

app/helpers/doacaos_helper.rb
module DoacaosHelper
end

app/views/doacaos/_form.html.haml
= form_for @doacao do |f|
  - if @doacao.errors.any?
    #error_explanation
      %h2= "#{pluralize(@doacao.errors.count, "error")} prohibited this doacao from being saved:"
      %ul
        - @doacao.errors.full_messages.each do |msg|
          %li= msg
  
  - @objeto = Objeto.where(id: params[:objeto_id]).first
  .separador
  %form
    %fieldset
      .categoriaForm     
        %h2 
          A instituicao
          = Instituicao.where(id: @objeto.instituicao_id).first.nome
          ainda necessita receber
          = @objeto.meta 
          = @objeto.unidade_medida 
          de 
          = @objeto.nome 
        .separador1
        .separador1
        .separador1
        .separador3
        .itemFormDoacao
          = f.label :quantidade, "Quanto voce gostaria de doar?", :class => "labelc"
          %br
          .itemFormDoacaoQuantidade
            = f.text_field :quantidade, :class => "inputd"
            = @objeto.unidade_medida
          %br
        .separador1
        .itemFormDoacao
          = f.label :observacoes, "Você gostaria de adicionar alguma observação?",:class => "labelc"
          %br
          = f.text_field :observacoes, :class => "inputb" 
        .field
          = f.hidden_field :status, :value => 0
        .field
          = f.hidden_field :usuario_id, :value => Usuario.find_by(email: Usuario.find(session[:userLogedIn]).email).id
        .field
          = f.hidden_field :objeto_id, :value => @objeto.id
        .separador1
        .separador1
        
        %div.div-submit-button
          = f.submit 'Doar', :class => "buttonForm"

app/views/doacaos/contato.html.haml
.separador1
%h1 
  Contato
.separador1   
.separador
.separador1     
.separador1     
%h2
  Entre em contato com 
  = @doacao.usuario.nome
  pelo e-mail 
  = @doacao.usuario.email
.separador1     
.separador1     
.separador2
.separador1  
.separador1     
.separador1     
-@href = "/doacaos/" + @doacao.id.to_s + "/conf_contato/"
%a{:href => @href }    
  .buttonbig
    .buttonlink FINALIZAR CONTATO
.separador1        
-@href1 = "/doacaos/" + @doacao.id.to_s + "/back_contato/"
%a{:href => @href1}    
  .buttonbig
    .buttonlink VOLTAR

app/views/doacaos/index.html.haml
.separador1
.separador1
.separador
.separador1
.itemObjeto
  .itemObjetoIcone
    -@imagem = "/images/logoinst.png"
    %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
  .itemObjetoNome
    %h1
      = @instituicao.nome
    .h2 
      = @instituicao.area_atuacao.nome
  .itemObjetoMeta
    %h2   
      = @instituicao.email
    .h3
      = @instituicao.cidade.nome
      = "-"
      = Estado.where(id: @instituicao.cidade.estado.id).first.sigla

.separador1
.separador1
.separador
%p
  %h2
    Doações recebidas
.separador2
- @doacaos.each do |doacao|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + doacao.objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = doacao.objeto.nome
      .h2 
        = doacao.quantidade
        = doacao.objeto.unidade_medida
    -case doacao.status
    -when 0  
      -@href = "/doacaos/" + doacao.id.to_s + "/contato"
      %a{:href => @href}
        -#ele ja esta alterando a tabela como contatado, tem que ser na pg de contato, o update ta na controller      
        .itemObjetoBotao
          .buttonlink
            CONTATO
      .itemObjetoMeta
        %h2   
          = doacao.usuario.nome
        .h3   
          = "Contato pendente"
    -when 1  
      -#não sei como eu chamo a função do controller aqui, alguem salva pf
      -@href = "/doacaos/" + doacao.id.to_s + "/aprovar?aprovar=sim"
      -@href1 = "/doacaos/" + doacao.id.to_s + "/aprovar?aprovar=nao"
      .itemObjetoBotao1.flex-button
        %a{:href => @href}
          .itemObjetoBotao1a
            .buttonlink
              CONFIRMAR
        .separador2
        %a{:href => @href1}
          .itemObjetoBotao1a
            .buttonlink  
              CANCELAR
      .itemObjetoMeta
        %h2   
          = doacao.usuario.nome
        .h3   
          = "Recebimento pendente"
    -when 2  
      
      .itemObjetoMeta
        %h2   
          = doacao.usuario.nome
        .h3   
          = "Cancelado"
    -else  
      .itemObjetoMeta
        %h2   
          = doacao.usuario.nome
        .h3   
          = doacao.observacoes
  .separador4
.separador1
.separador1
%a{:href => "/home/home"} 
  .button1
    .buttonlink VOLTAR
.separador1
.separador1
.separador2
.separador1
.separador1

app/views/doacaos/new.html.haml
%h1 Doação

= render 'form'

= link_to 'Back', doacaos_path

app/views/doacaos/show.html.haml
.separador3
.grupo2{style: "background-image: url('/images/background4.jpg'); height: 814px;"}
  .descrHome5
    %h1 Obrigado pela sua doação!
    %h2 Aguarde o contato da instituição para finalizar a doação

app/views/doacaos/success.html.haml
.separador3
.grupo2{style: "background-image: url('/images/background4.jpg'); height: 814px;"}
  .descrHome5
    %h1 Obrigado pela sua doação!
    %h2 Aguarde o contato da instituição para finalizar a doação