config/routes.rb
Rails.application.routes.draw do
  resources :objetos
  root 'home#index'
  get 'objetos/:id/destroy' => 'objetos#destroy'
  
  resources :instituicaos do
    collection do
      get 'details'
    end
  end
  post '/instituicaos/logoff' => 'instituicaos#logoff'
  
  # Rotas usuários
  resources :usuarios
    post '/usuarios/logoff' => 'usuarios#logoff'
    get '/usuarios/cadastro/doador' => 'usuarios#doador'
    get '/usuarios/cadastro/empresadoadora' => 'usuarios#empresadoadora'

  post '/usuarios/update_cidades' => 'usuarios#update_cidades'
  post '/instituicaos/update_cidades' => 'instituicaos#update_cidades'

  # Rotas login
  resources :login
    post '/login/auth' => 'login#auth'
  
  resources :layouts
  
  resources :doacaos  
    get '/doacoes/cadastro' => 'doacaos#new'
    get '/doacaos/:id/contato' => 'doacaos#contato'
    get '/doacaos/:id/conf_contato' => 'doacaos#conf_contato'
    get '/doacaos/:id/aprovar' => 'doacaos#aprovar'
    get '/doacaos/:id/back_contato' => 'doacaos#back_contato'
    
  get 'login/login'
  get 'home/index'
  get 'home/home'
  get 'home/cadastrousuariodoador'
  get 'about/about'
  get 'home/selectusertype'
  get 'instituicaos/listObjetos/:id' => 'instituicaos#listObjetos'
  
  post 'home/search' =>'home#search'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :cidade
  validates_confirmation_of :senha, :msg => "Confirmação de senha não confere com senha digitada."
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  def index
    @usuarios = nil
  end

  # GET /usuarios/1
  def show
    
  end
  
  def logoff
      session[:isLogedIn] = false
      session[:userLogedIn] = nil
      session[:isInstituicao] = false
      session[:instLogedin] = nil
      redirect_to "/home/index"
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new 
    @estados = get_lista_estados
    @cidades = get_lista_cidades(0)
  end

  # GET /usuarios/cadastro/doador
  def doador
    new
    render 'usuarios/new'
  end

  # GET /usuarios/cadastro/empresadoadora
  def empresadoadora
    new
    @usuario.isPJ = true
    render 'usuarios/new'
  end

  # GET /usuarios/1/edit
  def edit
    @estados = get_lista_estados
    @cidades = get_lista_cidades(@usuario.cidade.estado.id)
  end

  # POST /usuarios
  def create
    @usuario = Usuario.new(usuario_params)
    respond_to do |format|
      if(Usuario.exists?(email: @usuario.email) || Instituicao.exists?(email:  @usuario.email))
        flash.now[:alert]="E-mail já cadastrado"
        new
        format.html { render 'usuarios/new'}
      else 
        if(Usuario.exists?(documento: @usuario.documento))
          flash.now[:alert]=@usuario.isPJ ? "CNPJ" : "CPF" + " já cadastrado"
          new
          format.html { render 'usuarios/new'}
        else
          if @usuario.save
            session[:isLogedIn] = true
            session[:userLogedIn] = @usuario.id
            format.html { redirect_to '/home/home', notice: 'Cadastro realizado com sucesso!'}
          else
            new
            format.html { render :new }
          end
        end
      end
    end
  end

  # PATCH/PUT /usuarios/1
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Dados do usuário atualizados.' }
      else
        format.html { render :edit }
      end
    end
  end

  def update_cidades
    @cidades = get_lista_cidades(params[:estado_id] == '' ? 0 : params[:estado_id])
    render partial: "/cidades", locals: {cidades: @cidades}
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario deletado.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      if session[:isLogedIn]
        @usuario = Usuario.find(session[:userLogedIn])
      else
        @usuario = Usuario.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:documento, :nome, :email, :senha, :senha_confirmation, :cidade_id, :isPJ, :isInstituicao)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.haml
= form_for @usuario do |f|
  - if @usuario.errors.any?
    #error_explanation
    %h2= "#{pluralize(@usuario.errors.count, "error")} prohibited this usuario from being saved:"
    
    %ul
      - @usuario.errors.full_messages.each do |msg|
        %li= msg

  - if flash[:alert]
    %h2= flash[:alert]
  
 

  .form 
    %fieldset
      .categoriaForm     
        %h2 Dados do Usuário
        .separador
        .itemForm
          = f.label :documento, @usuario.isPJ ? "CNPJ" : "CPF", :class => "labela"
          = f.text_field :documento, :class => "inputa"
        .itemForm
          = f.label :nome, :class => "labela"
          = f.text_field :nome, :class => "inputa"
        .itemForm
          = f.label :email, "E-mail", :class => "labela"
          = f.email_field :email, :class => "inputa"
        .itemForm
          = f.label :senha, :class => "labela"
          = f.password_field :senha, :class => "inputa"
        .itemForm
          = label :senha_confirmation, "Confirmar senha",:class => "labela"
          = f.password_field :senha_confirmation, :class => "inputa"
          = f.hidden_field :isPJ, :value => @usuario.isPJ 
        .itemForm
          = label "estado","Estado", :class => "labela"
          = select_tag "estado", options_for_select(@estados), :class => "inputa" 
        .itemForm
          = f.label :cidade_id, :class => "labela"
          = f.select :cidade_id, options_for_select(@cidades), {:value => @usuario.cidade}, {:class => "inputa" }
        %div.div-submit-button
          = f.submit 'Finalizar', :class => "buttonForm"

app/views/usuarios/edit.html.haml
-if session[:isLogedIn] = true
  %h1 Editar dados do usuario
    
  = render 'form'

app/views/usuarios/index.html.haml
%h1 Usuários cadastrados

%table
  %thead
    %tr
      %th Documento
      %th Nome
      %th Email
      %th Cidade
      %th Empresa
      %th
      %th
      %th

  %tbody
    - @usuarios.each do |usuario|
      %tr
        %td= usuario.documento
        %td= usuario.nome
        %td= usuario.email
        %td= usuario.cidade.nome
        %td= usuario.isPJ ? "Sim" : "Não"
        %td= link_to 'Ver', usuario
        %td= link_to 'Editar', edit_usuario_path(usuario)
        %td= link_to 'Excluir', usuario, :method => :delete, :data => { :confirm => 'Confirmar exclusão?' }

%br

= link_to 'Cadastrar novo usuário', new_usuario_path

app/views/usuarios/instituicao.html.haml
.separador1
.separador1
.separador
.separador1
%p
  %h1 
    = @usuario.nome
%p
  %h2
    = @usuario.email
.separador2
%p
- if @usuario.isPJ?
  %p
    %h2 
      CNPJ:
      = @usuario.documento

- if !@usuario.isPJ?
  %p
    %h2 
      CPF:
      = @usuario.documento
%p
  %h2
    = @usuario.cidade.nome
    = "-"
    = Estado.where(id: @usuario.cidade.estado.id).first.sigla

.separador2
.separador1
.separador1
%h3 Quer atualizar alguma informação?
.separador1
%a{:href => edit_usuario_path(@usuario)}    
  .button2
    .buttonlink EDITAR
.separador1      
.separador1

%form{ :controller => 'usuarios', :action => 'logoff', :method => 'post' }
  .categoriaForm
    %input{ :type => "submit" , :class => "buttonForm1", :value => "SAIR"}
  

app/views/usuarios/new.html.erb
<%= form_for @usuario, url: {action: "create"} do |f| %>
    <div class="grupo1">
        <h2>Cadastro de usuarios - <%= @usuario.isPJ ? "Empresa" : "Pessoa Física"  %></h2>
    </div>
    <% if @usuario.errors.any? %>
        <div id="error_explanation">
            <h2> <%= pluralize(@usuario.errors.count, "error") %> usuario não pode ser salvo: </h2>
            <%= @usuario.errors.full_messages.each do |msg| %>
            <ul>
              <li></li> <%= msg %> </li>
            </ul>
            <% end %>
        </div>
    <% end %>
    <div class="grupo1">
        <%= f.label :documento, @usuario.isPJ ? "CNPJ:" : "CPF:" %>
        <%= f.text_field :documento, :required => true %>
    </div>
    <br>
    <div class="grupo1">
        <%= f.label :nome, "Nome:" %>
        <%= f.text_field :nome, :required => true %>
    </div>
    <br>
    <div class="grupo1">
        <%= f.label :email, "E-mail:" %>
        <%= f.email_field :email, :required => true %>
    </div>
    <br>
    <div class="grupo1">
        <%= f.label :senha, "Senha: " %>
        <%= f.password_field :senha, :required => true %>
    </div>
    <br>
    
    <div class="grupo1">
        <%= label "estado", "Estado:"%>
        <%= select_tag "estado", options_for_select(@estados), required: true %>
    </div>
    <br>
    
    <!-- Campo escondido para passar o valor que define se usuário é empresa como parâmetro do form -->
    <%= f.hidden_field :isPJ, :value => @usuario.isPJ  %>
    
    <div class="grupo1" id="div_cidades">
        <%= f.label :cidade_id, "Cidade: " %>
        <%= f.select :cidade_id, options_for_select(@cidades), required: true %>
    </div>
    <br>
    
    <div class="buttonlink">
        <%= f.submit "Cadastrar" %><br>
    </div>
<% end %>

app/views/usuarios/new.html.haml
%h1 Novo Usuario

= render 'form'

= link_to 'Back', usuarios_path

app/views/usuarios/show.html.haml
%p#notice= notice
.separador1
.separador1
.separador
.separador1
%p
  %h1 
    = @usuario.nome
%p
  %h2
    = @usuario.email
.separador2
%p
- if @usuario.isPJ?
  %p
    %h2 
      CNPJ:
      = @usuario.documento

- if !@usuario.isPJ?
  %p
    %h2 
      CPF:
      = @usuario.documento
%p
  %h2
    = @usuario.cidade.nome
    = "-"
    = Estado.where(id: @usuario.cidade.estado.id).first.sigla

.separador2
.separador1
.separador1
%h3 Quer atualizar alguma informação?
.separador1
%a{:href => edit_usuario_path(@usuario)}    
  .button2
    .buttonlink EDITAR
.separador1      
.separador1

%form{ :controller => 'usuarios', :action => 'logoff', :method => 'post' }
  .categoriaForm
    %input{ :type => "submit" , :class => "buttonForm1", :value => "SAIR"}
  