config/routes.rb
Rails.application.routes.draw do
  resources :objetos
  root 'home#index'
  get 'objetos/:id/destroy' => 'objetos#destroy'
  
  resources :instituicaos do
    collection do
      get 'details'
    end
  end
  post '/instituicaos/logoff' => 'instituicaos#logoff'
  
  # Rotas usuários
  resources :usuarios
    post '/usuarios/logoff' => 'usuarios#logoff'
    get '/usuarios/cadastro/doador' => 'usuarios#doador'
    get '/usuarios/cadastro/empresadoadora' => 'usuarios#empresadoadora'

  post '/usuarios/update_cidades' => 'usuarios#update_cidades'
  post '/instituicaos/update_cidades' => 'instituicaos#update_cidades'

  # Rotas login
  resources :login
    post '/login/auth' => 'login#auth'
  
  resources :layouts
  
  resources :doacaos  
    get '/doacoes/cadastro' => 'doacaos#new'
    get '/doacaos/:id/contato' => 'doacaos#contato'
    get '/doacaos/:id/conf_contato' => 'doacaos#conf_contato'
    get '/doacaos/:id/aprovar' => 'doacaos#aprovar'
    get '/doacaos/:id/back_contato' => 'doacaos#back_contato'
    
  get 'login/login'
  get 'home/index'
  get 'home/home'
  get 'home/cadastrousuariodoador'
  get 'about/about'
  get 'home/selectusertype'
  get 'instituicaos/listObjetos/:id' => 'instituicaos#listObjetos'
  
  post 'home/search' =>'home#search'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
  belongs_to :area_atuacao
  belongs_to :cidade
end

app/controllers/instituicaos_controller.rb
class InstituicaosController < ApplicationController
  before_action :set_instituicao, only: [:show, :edit, :update, :destroy]

  # GET /instituicaos
  def index
    @areas_atuacao = get_lista_areas_atuacao
    if(params.has_key?(:query))
      @instituicaos = Instituicao.where("area_atuacao_id in (?)", params[:query])
    else
      @instituicaos = Instituicao.all
    end
  end

  # GET /instituicaos/details
  def details
  end

  # GET /instituicaos/1
  def show
  end
  
  # GET instituicaos/listObjetos/1
  def listObjetos
    @instituicao = Instituicao.find(params[:id])
    @objetos = Objeto.where(:instituicao_id => params[:id]).where.not(is_inativo: true)
  end

  def logoff
      session[:isLogedIn] = false
      session[:userLogedIn] = nil
      session[:isInstituicao] = false
      session[:instLogedin] = nil
      redirect_to "/home/index"
  end

  # GET /instituicaos/new
  def new
    @instituicao = Instituicao.new
    @areas_atuacao = get_lista_areas_atuacao
    @estados = get_lista_estados
    @cidades = get_lista_cidades(0)
  end

  # GET /instituicaos/1/edit
  def edit
    @areas_atuacao = get_lista_areas_atuacao
    @estados = get_lista_estados
    @cidades = get_lista_cidades(@instituicao.cidade.estado.id)
  end

  # POST /instituicaos
  def create
    @instituicao = Instituicao.new(instituicao_params)
    @areas_atuacao = get_lista_areas_atuacao
    @estados = get_lista_estados
    @cidades = get_lista_cidades(@instituicao.cidade.estado.id)
    
    respond_to do |format|
      if(Instituicao.exists?(email: @instituicao.email) || Usuario.exists?(email:  @instituicao.email))
        flash.now[:alert]="E-mail já cadastrado"
        new
        format.html { render 'instituicaos/new'}
      else
        if(Instituicao.exists?(documento: @instituicao.documento))
          flash.now[:alert]="CNPJ já cadastrado"
          new
          format.html { render 'instituicaos/new'}
        else
          if @instituicao.save
            session[:isLogedIn] = true
            session[:isInstituicao] = true
            session[:instLogedin] = @instituicao.id
            format.html { redirect_to '/home/home', notice: 'Cadastro realizado com sucesso!' }
          else
            format.html { render :new }
          end
        end
      end
    end
  end
 

  # PATCH/PUT /instituicaos/1
  def update
    respond_to do |format|
      if @instituicao.update(instituicao_params)
        format.html { redirect_to @instituicao, notice: 'Instituicao was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def update_cidades
    @cidades = get_lista_cidades(params[:estado_id] == '' ? 0 : params[:estado_id])
    @areas_atuacao = get_lista_areas_atuacao
    render partial: "/cidades", locals: {cidades: @cidades}
  end

  # DELETE /instituicaos/1
  def destroy
    @instituicao.destroy
    respond_to do |format|
      format.html { redirect_to instituicaos_url, notice: 'Instituicao was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instituicao
      if(params.has_key?(:id) && params[:id] != "details")
        @instituicao = Instituicao.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instituicao_params
      params.require(:instituicao).permit(:area_atuacao_id, :documento, :nome, :email, :senha, :codigo, :cidade_id)
    end
end

app/helpers/instituicaos_helper.rb
module InstituicaosHelper
end

app/views/instituicaos/_form.html.haml
= form_for @instituicao do |f|
  - if @instituicao.errors.any?
    #error_explanation
      %h2= "#{pluralize(@instituicao.errors.count, "error")} prohibited this instituicao from being saved:"
      %ul
        - @instituicao.errors.full_messages.each do |msg|
          %li= msg

  - if flash[:alert]
    %h2= flash[:alert]


  .form 
    %fieldset
      .categoriaForm     
        %h2 Dados da Instituição
        .separador
        .itemForm
          = f.label :documento, "CNPJ",  :class => "labela"
          = f.text_field :documento, :class => "inputa"
        .itemForm
          = f.label :nome, :class => "labela"
          = f.text_field :nome, :class => "inputa"
        .itemForm
          = f.label :email, "E-mail", :class => "labela"
          = f.email_field :email, :class => "inputa"
        .itemForm
          = f.label :senha, :class => "labela"
          = f.password_field :senha, :class => "inputa"
        .itemForm
          = label "cfsenha", "Confirmar senha",:class => "labela"
          %input{:name => "cfsenha", :type => "password", :value => "", :class => "inputa"}/
        .itemForm
          = f.label :area_atuacao_id, "Area de atuação", :class => "labela"
          = f.select :area_atuacao_id, options_for_select(@areas_atuacao), {}, { :class => "inputa" }
        .itemForm
          = label "estado","Estado", :class => "labela"
          = select_tag "estado", options_for_select(@estados), :class => "inputa" 
        .itemForm
          = f.label :cidade_id, :class => "labela"
          = f.select :cidade_id, options_for_select(@cidades), {}, { :class => "inputa" }
        %div.div-submit-button
          = f.submit 'Finalizar', :class => "buttonForm"

app/views/instituicaos/details.html.haml
.separador1
.separador1
.separador
.separador1

- if session[:isLogedIn]
  - @instituicao = Instituicao.find(session[:instLogedin])
  
%p
  %h1 
    = @instituicao.nome
%p
  %h2
    = @instituicao.email
.separador2
%p
  %h2 
    CNPJ:
    = @instituicao.documento
    %p
  %h2 
    Area de Atuação: 
    = @instituicao.area_atuacao.nome
%p
  %h2
    = @instituicao.cidade.nome
    = "-"
    = Estado.where(id: @instituicao.cidade.estado.id).first.sigla

.separador2

.separador1
%h3 Quer atualizar alguma informação?
.separador1
%a{:href => edit_instituicao_path(@instituicao)}    
  .button2
    .buttonlink EDITAR
.separador1      
.separador2
.separador1
%form{ :controller => 'usuarios', :action => 'logoff', :method => 'post' }
  .categoriaForm
    %input{ :type => "submit" , :class => "buttonForm1", :value => "SAIR"}
  

app/views/instituicaos/edit.html.haml
%h1 Editar Instituição

= render 'form'

app/views/instituicaos/index.html.haml
.separador1
.h1 Lista de Instituições

.separador1
%form{ :controller => 'instituicaos', :method => 'get' }
  .categoriaForm
    .itemFormLogin
      %h3{ :style => 'display: inline' } Área de atuação:
      = select_tag "query", options_for_select(@areas_atuacao), :class => "inputa"
      %input{ :type => "submit" , :class => "buttonForm", :value => "FILTRAR"}
.separador1
.separador
- @instituicaos.each do |instituicao|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/logoinst.png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = instituicao.nome
      .h2 
        = instituicao.area_atuacao.nome
    %a{:href => "instituicaos/" + instituicao.id.to_s}    
      .itemObjetoBotao
        .buttonlink
          VER
    .itemObjetoMeta
      %h2   
        = instituicao.email
      .h3
        = instituicao.cidade.nome
        = "-"
        = Estado.where(id: instituicao.cidade.estado.id).first.sigla
  .separador4
.separador1
.separador1
%a{:href => "/home/home"} 
  .button1
    .buttonlink VOLTAR
.separador1
.separador1
.separador2

app/views/instituicaos/listObjetos.html.haml
.separador1
.separador1
.separador
.separador1
.itemObjeto
  .itemObjetoIcone
    -@imagem = "/images/logoinst.png"
    %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
  .itemObjetoNome
    %h1
      = @instituicao.nome
    .h2 
      = @instituicao.area_atuacao.nome
  .itemObjetoMeta
    %h2   
      = @instituicao.email
    .h3
      = @instituicao.cidade.nome
      = "-"
      = Estado.where(id: @instituicao.cidade.estado.id).first.sigla

.separador1
.separador1
.separador

%p
  %h2
    Objetos cadastrados
.separador2
- @objetos = Objeto.where(instituicao_id: @instituicao.id).where.not(is_inativo: true)
- @objetos.each do |objeto|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Icone", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = objeto.nome
      .h2 
        = objeto.observacoes
    
    %a{:href => edit_objeto_path(:id => objeto)}  
      .itemObjetoBotao
        .buttonlink
          EDITAR
    .itemObjetoMeta
      %h2
        Meta:
        = objeto.meta 
        = " "
        = objeto.unidade_medida
  .separador4
.separador1
%h2 Gostaria de cadastrar mais algum objeto?
%a{:href => "/objetos/new"}    
  .buttonbig
    .buttonlink CADASTRAR
.separador1
.separador1

app/views/instituicaos/ne1w.html.erb
<%= form_for @instituicao, url: {action: "create"} do |f| %>
    <div class="grupo2">
        <h2>Cadastro de Insituição </h2>
    </div>
    <% if @instituicao.errors.any? %>
        <div id="error_explanation">
            <h2> <%= pluralize(@instituicao.errors.count, "error") %> prohibited this instituicao from being saved: </h2>
            <%= @instituicao.errors.full_messages.each do |msg| %>
            <ul>
              <li></li> <%= msg %> </li>
            </ul>
            <% end %>
        </div>
    <% end %>
     <div class="grupo2">
        <%= f.label :email, "E-mail:" %>
        <%= f.email_field :email %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :senha, "Senha: " %>
        <%= f.password_field :senha %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :documento, "Documento:" %>
        <%= f.text_field :documento, :required => true %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :area_atuacao_id, "Área de atuação:" %>
        <%= f.select :area_atuacao_id, options_for_select(@areas_atuacao), required: true %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :nome, "Nome:" %>
        <%= f.text_field :nome %>
    </div>
    <br>
    <div class="grupo2">
        <%= label "estado", "Estado:"%>
        <%= select_tag "estado", options_for_select(@estados), required: true %>
    </div>
    <br>
    <div class="grupo2" id="div_cidades">
        <%= f.label :cidade_id, "Cidade: " %>
        <%= f.select :cidade_id, options_for_select(@cidades), required: true %>
    </div>
    <br>
    
    <div class="buttonlink">
        <%= f.submit "Cadastrar" %><br>
    </div>
<% end %>

app/views/instituicaos/new.html.erb
<%= form_for @instituicao, url: {action: "create"} do |f| %>
    <div class="grupo2">
        <h2>Cadastro de Insituição </h2>
    </div>
    <% if @instituicao.errors.any? %>
        <div id="error_explanation">
            <h2> <%= pluralize(@instituicao.errors.count, "error") %> prohibited this instituicao from being saved: </h2>
            <%= @instituicao.errors.full_messages.each do |msg| %>
            <ul>
              <li></li> <%= msg %> </li>
            </ul>
            <% end %>
        </div>
    <% end %>
     <div class="grupo2">
        <%= f.label :email, "E-mail:" %>
        <%= f.email_field :email %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :senha, "Senha: " %>
        <%= f.password_field :senha %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :documento, "Documento:" %>
        <%= f.text_field :documento, :required => true %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :area_atuacao_id, "Área de atuação:" %>
        <%= f.select :area_atuacao_id, options_for_select(@areas_atuacao), required: true %>
    </div>
    <br>
    <div class="grupo2">
        <%= f.label :nome, "Nome:" %>
        <%= f.text_field :nome %>
    </div>
    <br>
    <div class="grupo2">
        <%= label "estado", "Estado:"%>
        <%= select_tag "estado", options_for_select(@estados), required: true %>
    </div>
    <br>
    <div class="grupo2" id="div_cidades">
        <%= f.label :cidade_id, "Cidade: " %>
        <%= f.select :cidade_id, options_for_select(@cidades), required: true %>
    </div>
    <br>
    
    <div class="buttonlink">
        <%= f.submit "Cadastrar" %><br>
    </div>
<% end %>

app/views/instituicaos/new.html.haml
%h1 Nova Instituição
= @cfsenha

= render 'form'

= link_to 'Back', instituicaos_path

app/views/instituicaos/show.html.haml
.separador1
.separador1
.separador
.separador1
.itemObjeto
  .itemObjetoIcone
    -@imagem = "/images/logoinst.png"
    %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
  .itemObjetoNome
    %h1
      = @instituicao.nome
    .h2 
      = @instituicao.area_atuacao.nome
  .itemObjetoMeta
    %h2   
      = @instituicao.email
    .h3
      = @instituicao.cidade.nome
      = "-"
      = Estado.where(id: @instituicao.cidade.estado.id).first.sigla

.separador1
.separador1
.separador

%p
  %h2
    Objetos aceitos
.separador2
- @objetos = Objeto.where(instituicao_id: @instituicao.id).where.not(is_inativo: true)
- @objetos.each do |objeto|
  .itemObjeto
    .itemObjetoIcone
      -@imagem = "/images/catgs/catg" + objeto.categoria_objeto_id.to_s +  ".png"
      %img{:alt => "Doador Pessoa", :src => @imagem, :width => "90px"}/
    .itemObjetoNome
      %h1
        = objeto.nome
      .h2 
        = objeto.observacoes
    -if session[:isInstituicao]
      %a{:href => edit_objeto_path(@usuario)}    
        .itemObjetoBotao
          .buttonlink
            EXCLUIR
    -else
      %a{:href => new_doacao_path(:objeto_id => objeto)}  
        .itemObjetoBotao
          .buttonlink
            DOAR
    .itemObjetoMeta
      %h2
        Meta:
        = objeto.meta 
        = " "
        = objeto.unidade_medida
  .separador4
.separador1
.separador1